# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kevinrf
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fastapi-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: EmailService

provider:
  name: aws
  runtime: python3.12
  environment: # Global environment variables
    SMTP_SERVER: smtp.gmail.com
    SMTP_PORT: 587
    SENDER_EMAIL: ${env:SENDER_EMAIL}
    SENDER_PASSWORD: ${env:SENDER_PASSWORD}

functions:
  send_email:
    handler: handler.send_email
    environment: # Function-specific environment variables (optional)
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SENDER_EMAIL: ${env:SENDER_EMAIL}
      SENDER_PASSWORD: ${env:SENDER_PASSWORD}


